config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :chores

  root 'chores#index'

end

app/models/chore.rb
class Chore < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :chores
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only: [:show, :edit, :update, :destroy]

  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.all.order(params[:sort])
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
  end

  # GET /chores/new
  def new
    @chore = Chore.new
    @chore.user_id = params[:user]
    @chore.status = params[:status]
  end

  # GET /chores/1/edit
  def edit
  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = Chore.new(chore_params)
    @chore.user_id = params[:user]

    respond_to do |format|
      if @chore.save
        format.html { redirect_to chores_path, notice: 'Chore was successfully created.' }
        format.json { render :show, status: :created, location: chores_path }
      else
        format.html { render :new }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chores/1
  # PATCH/PUT /chores/1.json
  def update
    @chore = Chore.find(params[:id])
    @chore.user_id = params[:user]
    @chore.status = params[:status]
    respond_to do |format|
      if @chore.update(chore_params)
        format.html { redirect_to chores_path, notice: 'Chore was successfully updated.' }
        format.json { render :show, status: :ok, location: chores_path }
      else
        format.html { render :edit }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore.destroy
    respond_to do |format|
      format.html { redirect_to chores_url, notice: 'Chore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chore
      @chore = Chore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chore_params
      params.require(:chore).permit(:title, :description, :user_id, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to chores_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: chores_path }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to chores_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: chores_path }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to chores_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
  def sort_chores
    "#{params[:sort_by]}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>:<br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>:<br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user %>:<br>
    <%= select_tag "user", options_from_collection_for_select(User.all, "id", "name", 0) %>
  </div>
  <div class="field">
    <%= f.label :status %>:<br>
    <%= select_tag "status", options_for_select([['Not Started'], ['Doing'], ['Done']]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing Chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chores List</h1>

<div id='chores-container'>
  <% @chores.each do |chore| %>
    <div id='chore-container'>
      <p>
        <%= chore.id %> - <strong><%= chore.title %></strong>
        assigned to: <%= User.find(chore.user_id).name %>
      </p>
      <p>
        Status: <%= chore.status %>
      </p>
      <p>
        <%= link_to 'Edit', edit_chore_path(chore) %> |
        <%= link_to 'Delete', chore, method: :delete,
          data: {confirm: 'Are you sure?'} %>
      </p>
    </div>
    <br>
  <% end %>
</div>

<p><%= link_to_if User.any?, 'New Chore', new_chore_path %></p>
<p><%= link_to 'New Kid', new_user_path %></p>

app/views/chores/new.html.erb
<h1>New Chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chore.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @chore.description %>
</p>

<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChoreTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>